### ISSUE TITLE
uninitialized constant Nkss

### ISSUE THREAD

**Issue by flipactual** [nadarei/nkss-rails#5]
I get this error after adding nkss to a gem and then including that gem in a project and installing nkss in that project. Any help would be greatly appreciated. 

```
config/routes.rb:3:in `block in <top (required)>'
actionpack (3.2.11) lib/action_dispatch/routing/route_set.rb:282:in `instance_exec'
actionpack (3.2.11) lib/action_dispatch/routing/route_set.rb:282:in `eval_block'
actionpack (3.2.11) lib/action_dispatch/routing/route_set.rb:260:in `draw'
config/routes.rb:1:in `<top (required)>'
railties (3.2.11) lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
railties (3.2.11) lib/rails/application/routes_reloader.rb:40:in `each'
railties (3.2.11) lib/rails/application/routes_reloader.rb:40:in `load_paths'
railties (3.2.11) lib/rails/application/routes_reloader.rb:16:in `reload!'
railties (3.2.11) lib/rails/application/routes_reloader.rb:26:in `block in updater'
activesupport (3.2.11) lib/active_support/file_update_checker.rb:78:in `call'
activesupport (3.2.11) lib/active_support/file_update_checker.rb:78:in `execute'
activesupport (3.2.11) lib/active_support/file_update_checker.rb:86:in `execute_if_updated'
railties (3.2.11) lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
railties (3.2.11) lib/rails/application/finisher.rb:68:in `block (2 levels) in <module:Finisher>'
activesupport (3.2.11) lib/active_support/callbacks.rb:451:in `_run__201524332042655018__prepare__2127021988645328187__callbacks'
activesupport (3.2.11) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.11) lib/active_support/callbacks.rb:385:in `_run_prepare_callbacks'
activesupport (3.2.11) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.11) lib/action_dispatch/middleware/reloader.rb:74:in `prepare!'
actionpack (3.2.11) lib/action_dispatch/middleware/reloader.rb:64:in `call'
actionpack (3.2.11) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
actionpack (3.2.11) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
actionpack (3.2.11) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
railties (3.2.11) lib/rails/rack/logger.rb:32:in `call_app'
railties (3.2.11) lib/rails/rack/logger.rb:16:in `block in call'
activesupport (3.2.11) lib/active_support/tagged_logging.rb:22:in `tagged'
railties (3.2.11) lib/rails/rack/logger.rb:16:in `call'
quiet_assets (1.0.1) lib/quiet_assets.rb:20:in `call_with_quiet_assets'
actionpack (3.2.11) lib/action_dispatch/middleware/request_id.rb:22:in `call'
rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
rack (1.4.5) lib/rack/runtime.rb:17:in `call'
activesupport (3.2.11) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.4.5) lib/rack/lock.rb:15:in `call'
actionpack (3.2.11) lib/action_dispatch/middleware/static.rb:62:in `call'
railties (3.2.11) lib/rails/engine.rb:479:in `call'
railties (3.2.11) lib/rails/application.rb:223:in `call'
rack (1.4.5) lib/rack/content_length.rb:14:in `call'
railties (3.2.11) lib/rails/rack/log_tailer.rb:17:in `call'
thin (1.5.1) lib/thin/connection.rb:81:in `block in pre_process'
thin (1.5.1) lib/thin/connection.rb:79:in `catch'
thin (1.5.1) lib/thin/connection.rb:79:in `pre_process'
thin (1.5.1) lib/thin/connection.rb:54:in `process'
thin (1.5.1) lib/thin/connection.rb:39:in `receive_data'
eventmachine (1.0.3) lib/eventmachine.rb:187:in `run_machine'
eventmachine (1.0.3) lib/eventmachine.rb:187:in `run'
thin (1.5.1) lib/thin/backends/base.rb:63:in `start'
thin (1.5.1) lib/thin/server.rb:159:in `start'
rack (1.4.5) lib/rack/handler/thin.rb:13:in `run'
rack (1.4.5) lib/rack/server.rb:268:in `start'
railties (3.2.11) lib/rails/commands/server.rb:70:in `start'
railties (3.2.11) lib/rails/commands.rb:55:in `block in <top (required)>'
railties (3.2.11) lib/rails/commands.rb:50:in `tap'
railties (3.2.11) lib/rails/commands.rb:50:in `<top (required)>'
script/rails:6:in `require'
script/rails:6:in `<main>'
```

**Comment by rstacruz** [comment]
Thanks for the bug report! Please try restarting your Rails server first.
